### ISSUE TITLE
[Feature Request] When adding detect from image may I suggest that the UI assume the new image Size

### ISSUE THREAD

**Issue by shaneholloman** [fkunn1326/openpose-editor#20] opened 2023-02-20 00:28 UTC
When adding detect from image may I suggest that the UI assume the new image Size

**Comment by fkunn1326** [comment] 2023-02-20 00:40
Duplicate of #9

**Comment by fkunn1326** [comment] 2023-02-20 05:31
Fixed in 0ab0634

**Closed by fkunn1326** 2023-02-20 05:31 UTC
Labels: enhancement
